# Verwende ein offizielles Node.js-Image als Basis
FROM node:20

# Setze das Arbeitsverzeichnis im Container
WORKDIR /app

# Kopiere package.json und package-lock.json
COPY package*.json ./

# Installiere die Abhängigkeiten
RUN npm install

# Kopiere den Rest des Anwendungscodes
COPY . .

# Exponiere den Standard-Entwicklungsserver-Port
EXPOSE 4200

# Definiere den Befehl zum Starten der Anwendung
CMD ["npm", "start", "--", "--host", "0.0.0.0"]
